config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurantes
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    validates_presence_of :nome, message: " - deve ser preenchido"
    validates_uniqueness_of :nome, message: " - nome já cadastrado"
    validates_numericality_of :idade, greater_than: 0, less_than: 100, message: " - deve ser um número entre 0 e 100"
    has_many :qualificacoes
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :idade)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: @cliente, local: true, class: "form-horizontal") do |form| %>
<div class="row">
<div class="col-md-9">
 <%= render 'shared/form', obj: @cliente%>
 </div>
 </div>

  <div class="row">
<div class="col-md-3">   
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control" %>
  </div>
  </div>

<div class="row">
<div class="col-md-3">   
    <%= form.label :idade %>
    <%= form.number_field :idade, class: "form-control" %>
  </div>
  </div>

   <div class="form-group row justify-content-center">
    <%= form.submit class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>
<div class="container">
<%= render 'form', cliente: @cliente %>
</div>
<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<div class="container">
<div class="row">
 <div class="col-md-3">
<%= link_to 'Novo', {controller: 'clientes', action: 'new'},  { :class=>"btn btn-success" }  %>
<div>
</div>
<h1>Listagem de Clientes</h1>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to cliente.id,cliente_path(cliente) %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.idade %></td>
        <td><%= link_to 'Show', cliente %></td>
       <%= link_to 'Editar', {action: 'edit', controller: 'clientes', id: cliente}, {class: "btn btn-primary"} %>
        </td>
        <td>
        <%= link_to 'Deletar', {action: 'destroy', id: cliente},
        {method: "delete", confirmation: "Are you sure?", class: "btn btn-danger"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>
<div class="container">
<%= render 'form', cliente: @cliente %>
</div>
<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cliente.idade %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>