config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurantes
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
    validates_presence_of :nome, message: "deve ser preenchido"
    validates_presence_of :endereco, message: "deve ser preenchido"
    validates_presence_of :especialidade, message: "deve ser preenchido"
    validates_uniqueness_of :nome, message: "nome já cadastrado"
    validates_uniqueness_of :endereco, message: "endereço já cadastrado"
    validate :primeira_letra_deve_ser_maiuscula
    has_many :qualificacoes
    has_and_belongs_to_many :pratos

    has_many :qualificacoes
  
    private
    def primeira_letra_deve_ser_maiuscula
        errors.add(:nome,
        "primeira letra deve ser maiúscula") unless nome =~ /[A-Z].*/
    end


end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
    before_action :set_restaurante, only: [:edit, :update, :show, :destroy]
    def index
        @restaurantes = Restaurante.order :nome
    end

    def show
    end

    def destroy
        @restaurante = Restaurante.find(params[:id])
        @restaurante.destroy
        redirect_to(action: "index")
    end

    def new
        @restaurante = Restaurante.new
    end

    def edit
    end

    def update
        if@restaurante.update(restaurante_params)
            flash[:notice] = "Restaurante foi criado com sucesso"
            redirect_to restaurantes_path
        else
        render 'edit'
        end
    end
    

    def create
        @restaurante = Restaurante.new restaurante_params
        if @restaurante.save
            flash[:notice] = "Restaurante foi criado com sucesso"
            redirect_to restaurantes_path
        else 
            render 'new'
        end 
    end
    
    private 
    def set_restaurante
        @restaurante = Restaurante.find(params[:id])
    end

    def restaurante_params
        params.require(:restaurante).permit(:nome, :endereco, :especialidade)
    end
        
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_with(model: @restaurante, local: true, class: "form-horizontal")  do |f| %>
<div class="row">
<div class="col-md-9">
 <%= render 'shared/form', obj: @restaurante%>
 </div>
</div>
<div class="row">
<div class="col-md-3">
Nome: <%= f.text_field :nome, class:"form-control" %> <br/>
</div>
</div>
<div class="row">
<div class="col-md-3">
Endereço: <%= f.text_field :endereco, class:"form-control" %> <br/>
</div>
</div>
<div class="row">
<div class="col-md-3">
Especialidade: <%= f.text_field :especialidade, class:"form-control" %> <br/>
</div>
</div>
  <div class="form-group row justify-content-center">
   <%= f.submit class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1 class="text-center">Editar Restaurante</h1>
<div class="container-fluid">
<%= render 'form' %>
</div>

app/views/restaurantes/index.html.erb
<div class="container">
<div class="row">
 <div class="col-md-3">
<div>
<%= link_to 'Novo', {controller: 'restaurantes', action: 'new'},  { :class=>"btn btn-success" }  %>
</div>
</div>
<h1>Listagem de Restaurantes</h1>
<div class="row">
<table class="table">
<tr>
<th>ID</th>
<th>Nome</th>
<th>Endereço</th>
<th>Especialidade</th>
<th colspan="2"></th>
</tr>
<% @restaurantes.each do |restaurante| %>
<tr>
<td><%= link_to restaurante.id,restaurante_path(restaurante) %></td>
<td><%= restaurante.nome %> </td>
<td><%= restaurante.endereco %> </td>
<td><%= restaurante.especialidade %> </td>
<td>
<%= link_to 'Editar', {action: 'edit', controller: 'restaurantes', id: restaurante}, {class: "btn btn-primary"} %>
</td>
<td>
<%= link_to 'Deletar', {action: 'destroy', id: restaurante},
{method: "delete", confirmation: "Are you sure?", class: "btn btn-danger"} %>
</td>
</tr>
<% end %>
</table>
</div>

app/views/restaurantes/new.html.erb
<h1 class="text-center">Novo Restaurante</h1>
<div class="container">
<%= render 'form' %>
</div>

app/views/restaurantes/show.html.erb
<h1>Exibindo Restaurante</h1>
<p>
<b>Nome: </b>
<%= @restaurante.nome %>
</p>
<p>
<b>Endereço: </b>
<%= @restaurante.endereco %>
</p>
<p>
<b>Especialidade: </b>
<%= @restaurante.especialidade %>
</p>
<b>Nota média: </b>
<%= @restaurante.qualificacoes.average(:nota) %> <br/>
<b>Qualificações: </b>
<%= @restaurante.qualificacoes.count %> <br/>
<b>Preço médio: </b>
<%= @restaurante.qualificacoes.average(:valor_gasto) %> <br/><br/>