config/routes.rb
Rails.application.routes.draw do
  root :to => "home#index"
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurantes
end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
  before_action :set_qualificacao, only: %i[ show edit update destroy ]

  # GET /qualificacoes or /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all
  end

  # GET /qualificacoes/1 or /qualificacoes/1.json
  def show
  end

  # GET /qualificacoes/new
  def new
    @qualificacao = Qualificacao.new
    require_class
  end

  # GET /qualificacoes/1/edit
  def edit
    require_class
  end

  # POST /qualificacoes or /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(qualificacao_params)

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: "Qualificacao was successfully created." }
        format.json { render :show, status: :created, location: @qualificacao }
      else
        require_class
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualificacoes/1 or /qualificacoes/1.json
  def update
    respond_to do |format|
      if @qualificacao.update(qualificacao_params)
        format.html { redirect_to @qualificacao, notice: "Qualificacao was successfully updated." }
        format.json { render :show, status: :ok, location: @qualificacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1 or /qualificacoes/1.json
  def destroy
    @qualificacao.destroy
    respond_to do |format|
      format.html { redirect_to qualificacoes_url, notice: "Qualificacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualificacao
      @qualificacao = Qualificacao.find(params[:id])
    end

    def require_class
      @clientes = Cliente.all.pluck(:nome, :id)
      @restaurantes = Restaurante.all.pluck(:nome, :id)
    end
    

    # Only allow a list of trusted parameters through.
    def qualificacao_params
      params.require(:qualificacao).permit(:cliente_id, :restaurante_id, :nota, :valor_gasto)
    end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_with(model: @qualificacao, local: true, class: "form-horizontal")  do |form| %>
<div class="row">
<div class="col-md-9">
 <%= render 'shared/form', obj: @qualificacao%>
 </div>
 </div>
<div class="row">
<div class="col-md-3">   
 <%= form.label :cliente_id %>
 <%= form.select :cliente_id, @clientes,{}, {:class => 'form-control' } %>
 </div>
 </div>
<div class="row">
<div class="col-md-3">   
 <%= form.label :restaurante_id %>
 <%= form.select :restaurante_id, @restaurantes ,{}, {:class => 'form-control'} %>
 </div>
 </div>
<div class="row">
<div class="col-md-3">
    <%= form.label :nota %>
    <%= form.text_field :nota, class: 'form-control' %>
</div>
</div>
<div class="row">
<div class="col-md-3">
    <%= form.label :valor_gasto %>
    <%= form.text_field :valor_gasto, class: 'form-control' %>
</div>
</div>
</div>

   <div class="form-group row justify-content-center">
   <%= form.submit class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/qualificacoes/edit.html.erb
<h1 class="text-center">Atualizar Qualificacão</h1>
<div class="container">
<%= render 'form' %>
</div>

app/views/qualificacoes/index.html.erb
<div class="container">
<div class="row">
 <div class="col-md-3">
<%= link_to 'Novo', {controller: 'qualificacoes', action: 'new'},  { :class=>"btn btn-success" }  %>
</div>
</div>
<p id="notice"><%= notice %></p>

<h1>Qualificacoes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Restaurante</th>
      <th>Nota</th>
      <th>Valor gasto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qualificacoes.each do |qualificacao| %>
      <tr>
        <td><%= link_to qualificacao.id,qualificacao_path(qualificacao) %></td>
        <td><%= qualificacao.restaurante_id %></td>
        <td><%= qualificacao.nota %></td>
        <td><%= valor_formatado(qualificacao.valor_gasto) %></td>
       <td>
        <%= link_to 'Editar', {action: 'edit', controller: 'qualificacoes', id: qualificacao}, {class: "btn btn-primary"} %>
        </td>
        <td>
        <%= link_to 'Deletar', {action: 'destroy', id: qualificacao},
        {method: "delete", confirmation: "Are you sure?", class: "btn btn-danger"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qualificacao', new_qualificacao_path %>

app/views/qualificacoes/new.html.erb
<h1 class="text-center">Nova Qualificacão</h1>
<div class="container">
<%= render 'form' %>
</div>

app/views/qualificacoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @qualificacao.cliente_id %>
</p>

<p>
  <strong>Restaurante:</strong>
  <%= @qualificacao.restaurante_id %>
</p>

<p>
  <strong>Nota:</strong>
  <%= @qualificacao.nota %>
</p>

<p>
  <strong>Valor gasto:</strong>
  <%= @qualificacao.valor_gasto %>
</p>



<%= link_to 'Edit', edit_qualificacao_path(@qualificacao) %> |
<%= link_to 'Back', qualificacoes_path %>